SELECT [AcademicYear]
      ,[GenderCode]
      ,[OrgCode]
      ,[SchoolYear]
      ,[Bmi]
      ,[BmiZScore]
      ,[BmiPScore]
      ,[NcmpSchoolStatus]
      ,[NcmpSystemId]
      ,[BmiPopulationCategory]
      ,[NhsEthnicityCode]
      ,[NcmpEthnicityCode]
      ,[OrgCode_ONS]
      ,[RegionCode]
      ,[PupilRegionCode]
      ,[PupilTier1LocalAuthority]
      ,[PupilTier2LocalAuthority]
      ,[SchoolRegionCode]
      ,[SchoolTier1LocalAuthority]
      ,[SchoolTier2LocalAuthority]
      ,[PupilUrbanRuralIndicator]
      ,[PupilIndexOfMultipleDeprivationD]
      ,[SchoolIndexOfMultiDeprivationD]
      ,[SchoolUrbanRuralIndicator]
      ,[DateOfMeasurement]
      ,[PupilOnsSupergroupCode]
      ,[SchoolOnsSupergroupCode]
      ,[ExtractDate]
      ,[AgeInMonths]
      ,[SchoolUrn]
      ,[SchoolName]
      ,[SchoolPostcode]
      ,[WeightZScore]
      ,[HeightZScore]
      ,[PupilSchoolPostcodeDistance]
FROM [DATABASE].[SERVER].[TABLE]
WHERE [AcademicYear] = '<Year>'
